version: '3.1'

services:

  mysql:
    image: mysql
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: rasplus
      MYSQL_USER: bruno
      MYSQL_PASSWORD: senha123